### ISSUE TITLE
Add typescript to the --dev deps

### ISSUE THREAD

**Issue by chevdor** [pocesar/node-nxt-api#2]

**Comment by chevdor** [comment]
as well as chai, sinon

**Comment by pocesar** [comment]
usually typescript compiler is installed as a global, I could add it as a peerDependency, but that is being deprecated. chai and sinon are already set as devDependencies

**Comment by chevdor** [comment]
fair enough :) I would just mention it in the doc somewhere. I am not familiar with typescript and it took me a little while to realise that the missing tsc was that. At least the issue entry may help a few others.

**Comment by pocesar** [comment]
good point, need to update to 1.4 APIs and will add that note to the readme
